name: Auto Code Update Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  auto_update:
    runs-on: ubuntu-latest

    steps:

      # Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Python
      - name: Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Install Dependencies
      - name: Install Packages
        run: |
          python -m pip install --upgrade pip
          pip install gitpython pandas numpy scikit-learn joblib huggingface_hub

      # Run ML Pipeline Scripts
      - name: Run Automation Scripts
        run: |
          python src/data_preprocessing.py
          python src/train_model.py
          python src/evaluate_model.py

      # Commit Generated Updates
      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actionbot@github.com"

          git add My_Project/models || true
          git add My_Project/data/processed || true

          git commit -m "Auto pipeline update" || echo "No changes to commit"

      # Push Code Updates
      - name: Push to Main Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main